# Generated by Django 2.2 on 2019-04-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.TextField(default='web developer', max_length=50),
            preserve_default=False,
        ),
    ]
