# Generated by Django 2.2 on 2019-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190404_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(default='June 2011 to Present', max_length=50),
            preserve_default=False,
        ),
    ]
