# Generated by Django 2.2 on 2019-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_education_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='abcd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
