# Generated by Django 2.2 on 2019-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20190410_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.CharField(max_length=30),
        ),
    ]
