# Generated by Django 2.2 on 2019-04-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default='world', max_length=20),
            preserve_default=False,
        ),
    ]
